server:
  port: 9999

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/xdb?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  redis:
    port: 6379
    host: 192.168.80.128
    password: 1234

logging:
  level:
    com.lantu: debug